apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: topology-viewer
spec:
  version: v0.0.9
  homepage: https://github.com/TalShafir/topology-viewer
  shortDescription: Shows the topology of the cluster accross domains
  description: |-
    This plugin shows how the cluster is spread accross different domains.
    A domain is a different values of a node label (e.g different values of 'topology.kubernetes.io/zone').
    You can view how the nodes themselves are spread accross the topologies or pods with optional label selector.
  platforms:
    - bin: topology-viewer
      sha256: f71eecdcbab0e6a13fc16ed6fcf7cad6b3127a972dba07f57827ad7418c08637
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.9/topology-viewer_Darwin_arm64.tar.gz
      selector:
        matchLabels:
          os: darwin
          arch: arm64
    - bin: topology-viewer
      sha256: b6521cbb82222232050cac00d4163671782d93e57e093f2c092895154215832f
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.9/topology-viewer_Darwin_x86_64.tar.gz
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - bin: topology-viewer
      sha256: 69cbbc0ff42b8f37adb2ef645a5b53fa20dec0ffac8243dc92d8be203ad508d5
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.9/topology-viewer_Linux_arm64.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: arm64
    - bin: topology-viewer
      sha256: df7acb238f12c5a1b171b81ec35a6e7a0e1d846363d10aebf26d666ab7638000
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.9/topology-viewer_Linux_i386.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: "386"
    - bin: topology-viewer
      sha256: 6c63608c7ba759238200d78446394c39e435c8dd26f5330854c6bc4c2a34f144
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.9/topology-viewer_Linux_x86_64.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - bin: topology-viewer.exe
      sha256: aef49394e6eb6905a78ed31458ddde9ed353b1b44b7138102926d5d9522dcf8d
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.9/topology-viewer_Windows_arm64.zip
      selector:
        matchLabels:
          os: windows
          arch: arm64
    - bin: topology-viewer.exe
      sha256: b1f8da774f19a6b56afd4e74b16c6f42afa20334c287e34fca8dfbc187080791
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.9/topology-viewer_Windows_i386.zip
      selector:
        matchLabels:
          os: windows
          arch: "386"
    - bin: topology-viewer.exe
      sha256: 81256238324e69383f98972150fd60ff4742432b31b3761f2220dc4a99da1042
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.9/topology-viewer_Windows_x86_64.zip
      selector:
        matchLabels:
          os: windows
          arch: amd64
