apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: topology-viewer
spec:
  version: v0.0.6
  homepage: https://github.com/TalShafir/topology-viewer
  shortDescription: Shows the topology of the cluster accross domains
  description: |-
    This plugin shows how the cluster is spread accross different domains.
    A domain is a different values of a node label (e.g different values of 'topology.kubernetes.io/zone').
    You can view how the nodes themselves are spread accross the topologies or pods with optional label selector.
  platforms:
    - bin: topology-viewer.exe
      sha256: 53ac9ccf927c825f66f1ff79f4956dbb05c2946811575c5741be026178fc6b40
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.6/topology-viewer_Windows_i386.zip
      selector:
        matchLabels:
          os: windows
          arch: "386"
    - bin: topology-viewer.exe
      sha256: fc987a60a2f75f0417ea1194628501635ffaa1cd85f9b13edeb0540082702c96
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.6/topology-viewer_Windows_arm64.zip
      selector:
        matchLabels:
          os: windows
          arch: arm64
    - bin: topology-viewer
      sha256: db99dd16e0f6412dfbf5f73c4148e8640d458e5917998421acb343f901e49136
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.6/topology-viewer_Linux_x86_64.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - bin: topology-viewer.exe
      sha256: 868e1070832fa2b1a46c1c2acaf6adfef175b6d7eb129bc7a0210dd9f49cbb02
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.6/topology-viewer_Windows_x86_64.zip
      selector:
        matchLabels:
          os: windows
          arch: amd64
    - bin: topology-viewer
      sha256: ae8eee1c5ae5a2a4744b9be4a21aa760895b1ba6621630b69e9aac37de0117a4
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.6/topology-viewer_Darwin_arm64.tar.gz
      selector:
        matchLabels:
          os: darwin
          arch: arm64
    - bin: topology-viewer
      sha256: 7b8f929bf22d884924ef3a319d1a4741d20498b628e424182c37860dca716b02
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.6/topology-viewer_Linux_i386.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: "386"
    - bin: topology-viewer
      sha256: a5f54c394dcc741dc9eb5001ffab46cde8c7316929e8e5fdae4296cf084af1f2
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.6/topology-viewer_Darwin_x86_64.tar.gz
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - bin: topology-viewer
      sha256: 250232e2219834e0ad4c6f35718d2cd7ef145ad615600041568442854cd85fcd
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.6/topology-viewer_Linux_arm64.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: arm64
