apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: topology-viewer
spec:
  version: v0.0.8
  homepage: https://github.com/TalShafir/topology-viewer
  shortDescription: Shows the topology of the cluster accross domains
  description: |-
    This plugin shows how the cluster is spread accross different domains.
    A domain is a different values of a node label (e.g different values of 'topology.kubernetes.io/zone').
    You can view how the nodes themselves are spread accross the topologies or pods with optional label selector.
  platforms:
    - bin: topology-viewer
      sha256: 7a2f4952bbbdd251d9864fb19f430484a3f4c3d9b22dd0d1428da5a51e51dc48
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.8/topology-viewer_Darwin_arm64.tar.gz
      selector:
        matchLabels:
          os: darwin
          arch: arm64
    - bin: topology-viewer
      sha256: 6c95786dfe974d76e8aef6e07e8722772c9bc1c6364dc7dfbc413853c276d334
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.8/topology-viewer_Darwin_x86_64.tar.gz
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - bin: topology-viewer
      sha256: f62a657e7c18a34d35947f90df80e130074c9d99cd58de4d6b709b6fce7a11d1
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.8/topology-viewer_Linux_arm64.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: arm64
    - bin: topology-viewer
      sha256: 016796aae0c6ee69542c8bf11c6b88c9df33ecc7d60dbe4fbc6a213e23ef22ed
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.8/topology-viewer_Linux_i386.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: "386"
    - bin: topology-viewer
      sha256: 6a90a1d14c91a6ac468c935f1c1041e42cbe0471569cc03b15bfecde8528b8e2
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.8/topology-viewer_Linux_x86_64.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - bin: topology-viewer.exe
      sha256: 010e5c14af7e231bbc8d6abd12d58499a8b9fc0a24b040bd6af62fcbad45aa87
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.8/topology-viewer_Windows_arm64.zip
      selector:
        matchLabels:
          os: windows
          arch: arm64
    - bin: topology-viewer.exe
      sha256: 109dba6d6a03dd6dcbbe8e0318080a02e9c563d44101a54aa4c3842a5825989f
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.8/topology-viewer_Windows_i386.zip
      selector:
        matchLabels:
          os: windows
          arch: "386"
    - bin: topology-viewer.exe
      sha256: 3cf4faefc003f461519f8a7675fbded06db23d3ab31469de97ada8f892c7d869
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.8/topology-viewer_Windows_x86_64.zip
      selector:
        matchLabels:
          os: windows
          arch: amd64
