apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: topology-viewer
spec:
  version: v0.0.1
  homepage: https://github.com/TalShafir/topology-viewer
  shortDescription: Shows the topology of the cluster accross domains
  description: |-
    This plugin shows how the cluster is spread accross different domains.
    A domain is a different values of a node label (e.g different values of 'topology.kubernetes.io/zone').
    You can view how the nodes themselves are spread accross the topologies or pods with optional label selector.
  platforms:
    - bin: topology-viewer
      sha256: 5700058cae41daabe659e459968a56beed3dd95dcb92980124e6c8b86a1f803a
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.1/topology-viewer_Linux_i386.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: "386"
    - bin: topology-viewer
      sha256: 4695257081586e8ec4eb67b67a48ba7489419c8dbd4b73b9855c3a1d3106e5dd
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.1/topology-viewer_Darwin_arm64.tar.gz
      selector:
        matchLabels:
          os: darwin
          arch: arm64
    - bin: topology-viewer
      sha256: 6bb3ad7e20862dbc2b4c5da65d828eb2cf2d0efc9adc1ffb70a1c8926da610ab
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.1/topology-viewer_Linux_arm64.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: arm64
    - bin: topology-viewer
      sha256: 31081ba5506e524fc8828b21e8958e77f8f383dc8c337b8aff7d1989d687bcc0
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.1/topology-viewer_Darwin_x86_64.tar.gz
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - bin: topology-viewer.exe
      sha256: ebac4ba1bd0f882afbe14d5889a95d2ec14c42c487a6ccacce661295e5b2f5ac
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.1/topology-viewer_Windows_i386.zip
      selector:
        matchLabels:
          os: windows
          arch: "386"
    - bin: topology-viewer
      sha256: d0b938b5c626ac07742b90f06df2953716685feaf6f3ed6dd94266b8d9fbb7ed
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.1/topology-viewer_Linux_x86_64.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - bin: topology-viewer.exe
      sha256: ed0abac2e2ae380ad354514386a1007d07f97a7268f55762a3746cfb08ce8c83
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.1/topology-viewer_Windows_arm64.zip
      selector:
        matchLabels:
          os: windows
          arch: arm64
    - bin: topology-viewer.exe
      sha256: f9443cf9e311feafbbf1fc5a203ac6db9f30a36bcf2813bb304076bb2462fa5e
      uri: https://github.com/TalShafir/topology-viewer/releases/download/v0.0.1/topology-viewer_Windows_x86_64.zip
      selector:
        matchLabels:
          os: windows
          arch: amd64
