name: release
on:
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

    - name: Install yq
      uses: mikefarah/yq@v4.44.6
    - name: Install jq
      uses: dcarbone/install-jq-action@v3.0.1

    - name: Update Krew manifest
      run: bash update-manifest.sh
      env:
        TAG: ${{ github.ref_name }}
    
    - name: Commit manifest change
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update Krew manifest ${{ github.ref_name }}
        file_pattern: 'topology-viewer.yaml'

